### ISSUE TITLE
Prevent Default ActiveRecord Logging From Being Disabled

### ISSUE THREAD

**Issue by SeanTurner026** [iMacTia/lograge-sql#11]
This Gem disables default ActiveRecord logging. Is it possible to configure this behavior such that the default ActiveRecord logging remains enabled?

Reason being is that we currently have our logs going to Stackdriver. 

However, I am currently implementing Datadog logging. With the default ActiveRecord logging disabled, the sql queries no longer show up inside of Stackdriver. 

As such, I don't want to take away SQL logging from production Stackdriver before Datadog SQL logging is fully configured.

**Comment by iMacTia** [comment]
Hi @SeanTurner026, I’m afraid that’s not possible at the moment as I didn’t foresee such a situation.

A PR is welcome to disable the default behaviour with some sort of configuration.
Given that just requiring the file is enough to disable it, I’d suggest the use of an ENV variable. How does that sound?

**Comment by SeanTurner026** [comment]
Sounds good to me. 

Standard Lograge has: `config.lograge.keep_original_rails_log = true`

Perhaps something along the lines of: `config.lograge_sql.keep_default_active_record_log = true` would make sense

**Comment by iMacTia** [comment]
Sounds good!
