### ISSUE TITLE
Why isn't SQL no longer displaying?

### ISSUE THREAD

**Issue by gumatias** [iMacTia/lograge-sql#13]
Hello,

Any ideas why AR SQLs are not showing in `logs/test.log`?

I've got:

**Gemfile**
```
  gem 'lograge'
  gem 'lograge-sql'
```

**config/environments/test.rb**
```
require 'lograge/sql/extension'

Rails.application.configure do
  config.log_level = :debug
  config.lograge.enabled = true
  config.lograge.keep_original_rails_log = true
end
```

**Comment by iMacTia** [comment]
Hi!
This gem disables SQL logs by default, but it’s currently lacking an option to reenable them. An issue has already been opened for it (https://github.com/iMacTia/lograge-sql/issues/11), so I’m closing this one in favour of that.

**Comment by gumatias** [comment]
thanks @iMacTia ! the strange thing I noticed is that I see AR SQL for feature/Capybara specs, but no regular rspec ones. Is that also related? I thought I needed to change some settings.

**Comment by iMacTia** [comment]
Mmmmh that's curious, but it might depend on the gem not being loaded for some environment.
Do you see lograge logs when you run feature/Capybara specs? If those are also missing, it might be that the environment those tests are running in is not the same.

Now that I think about it, when you say `AR SQLs are not showing`, do you mean they don't appear in the lograge payload or that the default AR logs are not showing?
