### ISSUE TITLE
New release for Rails 6 support?

### ISSUE THREAD

**Issue by trammel** [iMacTia/lograge-sql#20]
Now that https://github.com/iMacTia/lograge-sql/commit/5145e7fb052b61ae70cae670f34866135842f94c is merged and (presumably) stable, would you mind doing a version bump and putting out a new release on rubygems?

**Comment by ibrasho** [comment]
Yes, please @iMacTia. 🌹

**Comment by iMacTia** [comment]
It fills me with joy to see others use and even contribute to this gem 😃 
So I figured it was time for a `v1.0.0` release ❤️ 
https://rubygems.org/gems/lograge-sql
