### ISSUE TITLE
Filtering out sensitive info in SQL logs

### ISSUE THREAD

**Issue by tjjjwxzq** [iMacTia/lograge-sql#50]
I was wondering how we would go about filtering any sensitive information that might be inside our SQL queries when using this gem. We are already using logstop to scrub our logs but it doesn't seem to work on the SQL logs when this gem is being used, as I still see data like email addresses in our SQL logs, which logstop should be scrubbing out.

**Comment by iMacTia** [comment]
I'm sure that would be an interesting addition to the gem!
[This method](https://github.com/iMacTia/lograge-sql/blob/master/lib/lograge/sql.rb#L50C43-L50C43) is where we extract the sql from the active support notification and concatenate it into the string message.

A good starting point would be to apply the filtering to `event.payload[:sql]` which is a simple SQL query string.
We could apply a configurable lambda to it (no-op by default) for the user to apply their own filtering. You could then reuse whatever solution you're already using in there. Something like:

```ruby
Rails.application.configure do
  config.lograge_sql.filter = -> (query) { Logstop.scrub(query) }
end
```

**Comment by tjjjwxzq** [comment]
Thanks for the context and a possible approach @iMacTia , I'll see if I can look into it
