### ISSUE TITLE
Compatibility with Rails 8

### ISSUE THREAD

**Issue by rubenfonseca** [iMacTia/lograge-sql#61]
Thank you for creating this package! I really appreciate your work on it.

I wanted to let you know that it’s not compatible with Rails 8. Could you please provide an update or guidance on this?

Thanks!

**Comment by iMacTia** [comment]
Hi @rubenfonseca and thank you for the kind words 🙇 !
To add support for new Rails, we just need to relax the `activerecord` version and add CI coverage.
you can see an example of how we did it for Rails 7.2 [here](https://github.com/iMacTia/lograge-sql/pull/58/files).
Would you like to give it a go for Rails 8? If not, I can get to it as soon as I have some time

**Comment by bpieck** [comment]
Hi,
I'll try with rails 8.

**Comment by fdaugs** [comment]
@bpieck

Had the same idea: https://github.com/iMacTia/lograge-sql/pull/62

@iMacTia I think the rails 8 support then also justifies its own release ;)

**Comment by iMacTia** [comment]
Thanks @fdaugs 🙇 
And yes agreed, I'll cut a release now. Should be on Rubygems soon 🚀

**Comment by fdaugs** [comment]
Thank for your support @iMacTia! 🥳
